apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::637423345584:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-S3R1hUbuqXIN
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::637423345584:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-05-20T21:24:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1248"
  uid: acdc21d1-fb39-4767-a505-7a298f046802
